# Generated by Django 2.0.5 on 2020-04-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_admin', '0002_auto_20200416_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantTypeModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
    ]
